In [1]:
from process_analyze_data import AnalyzeDataProcessor

# 커스텀 설정
processor = AnalyzeDataProcessor(api_url="http://localhost:8000")

# 특정 모델로 처리
results = processor.process_all_images(model="gpt-4o")

🔍 5개의 PNG 파일 발견
==================================================

[1/5] sample1.png
처리 중: sample1.png
✅ 성공: 1개 표 발견
💾 결과 저장: result\sample1_result.json
⏳ 1.0초 대기...

[2/5] sample2.png
처리 중: sample2.png
✅ 성공: 1개 표 발견
💾 결과 저장: result\sample2_result.json
⏳ 1.0초 대기...

[3/5] sample3.png
처리 중: sample3.png
✅ 성공: 1개 표 발견
💾 결과 저장: result\sample3_result.json
⏳ 1.0초 대기...

[4/5] sample4.png
처리 중: sample4.png
✅ 성공: 1개 표 발견
💾 결과 저장: result\sample4_result.json
⏳ 1.0초 대기...

[5/5] sample5.png
처리 중: sample5.png
✅ 성공: 1개 표 발견
💾 결과 저장: result\sample5_result.json

In [2]:
results

[{'success': True,
  'tables': [{'table_id': 'table_1',
    'title': "'25년 상반기 잠정 실적",
    'headers': ['회사', '매출', '영업이익 (%)', '세전이익 (%)'],
    'rows': [['당사', '70,149', '2,771 (4.0)', '3,245 (4.6)'],
     ['현대', '151,763', '4,307 (2.8)', '4,054 (2.7)'],
     ['GS', '62,590', '2,324 (3.7)', '△738 (△1.2)'],
     ['대우', '43,500', '2,335 (5.4)', '446 (1.0)'],
     ['DL', '37,996', '2,072 (5.5)', '672 (1.8)']],
    'row_count': 5,
    'column_count': 4}],
  'markdown': '| 회사 | 매출 | 영업이익 (%) | 세전이익 (%) |\n|------|------|-------------|-------------|\n| 당사 | 70,149 | 2,771 (4.0) | 3,245 (4.6) |\n| 현대 | 151,763 | 4,307 (2.8) | 4,054 (2.7) |\n| GS | 62,590 | 2,324 (3.7) | △738 (△1.2) |\n| 대우 | 43,500 | 2,335 (5.4) | 446 (1.0) |\n| DL | 37,996 | 2,072 (5.5) | 672 (1.8) |',
  'summary': "1개의 표가 발견되었습니다. 표는 '25년 상반기 잠정 실적'에 대한 정보를 포함하고 있으며, 5개의 회사에 대한 매출, 영업이익, 세전이익을 보여줍니다.",
  'table_count': 1,
  'extraction_method': 'OpenAI API (gpt-4o)'},
 {'success': True,
  'tables': [{'table_id': 'table_1',
    'title': "매출 및 이익 분석 ('23~'25)",
    'headers': ['구분',
     "'23年 연間",
     "'24年 1Q",
     "'24年 2Q",
     "'24年 上",
     "'24年 下",
     "'24年 계",
     "'25年 1Q",
     "'25年 2Q",
     "'25年 上"],
    'rows': [['매출액',
      '29.7',
      '8.5',
      '8.6',
      '17.2',
      '15.5',
      '32.7',
      '7.5',
      '7.7',
      '15.2'],
     ['영업이익',
      '7,854 (2.6%)',
      '2,509 (3.5%)',
      '1,473 (2.9%)',
      '3,982 (3.2%)',
      '△16,616 (△10.7%)',
      '△12,634 (△3.0%)',
      '2,137 (2.8%)',
      '2,170 (2.8%)',
      '4,307 (2.8%)'],
     ['세전이익',
      '9,395 (3.2%)',
      '3,028 (3.5%)',
      '2,478 (2.9%)',
      '5,506 (3.2%)',
      '△15,363 (△9.9%)',
      '△9,857 (△3.0%)',
      '2,053 (2.8%)',
      '2,001 (2.6%)',
      '4,054 (2.7%)']],
    'row_count': 3,
    'column_count': 10}],
  'markdown': "| 구분 | '23年 연間 | '24年 1Q | '24年 2Q | '24年 上 | '24年 下 | '24年 계 | '25年 1Q | '25年 2Q | '25年 上 |\n|---|---|---|---|---|---|---|---|---|---|\n| 매출액 | 29.7 | 8.5 | 8.6 | 17.2 | 15.5 | 32.7 | 7.5 | 7.7 | 15.2 |\n| 영업이익 | 7,854 (2.6%) | 2,509 (3.5%) | 1,473 (2.9%) | 3,982 (3.2%) | △16,616 (△10.7%) | △12,634 (△3.0%) | 2,137 (2.8%) | 2,170 (2.8%) | 4,307 (2.8%) |\n| 세전이익 | 9,395 (3.2%) | 3,028 (3.5%) | 2,478 (2.9%) | 5,506 (3.2%) | △15,363 (△9.9%) | △9,857 (△3.0%) | 2,053 (2.8%) | 2,001 (2.6%) | 4,054 (2.7%) |",
  'summary': '총 1개의 표가 발견되었습니다. 이 표는 2023년부터 2025년까지의 매출액, 영업이익, 세전이익을 분기별로 나타내고 있습니다.',
  'table_count': 1,
  'extraction_method': 'OpenAI API (gpt-4o)'},
 {'success': True,
  'tables': [{'table_id': 'table_1',
    'title': '매출 및 이익 분석',
    'headers': ['구분',
     "'23年",
     "'24年 1Q",
     "'24年 2Q",
     "'24年 24上",
     "'24年 24下",
     "'24年 계",
     "'25年 1Q",
     "'25年 2Q",
     "'25年 25上"],
    'rows': [['매출액',
      '13.4',
      '3.1',
      '3.3',
      '6.4',
      '6.5',
      '12.9',
      '3.1',
      '3.2',
      '6.3'],
     ['영업이익',
      '△3,879',
      '705',
      '934',
      '1,639',
      '1,221',
      '2,860',
      '704',
      '1,620',
      '2,324'],
     ['(%)',
      '(△2.9%)',
      '(2.3%)',
      '(2.3%)',
      '(2.6%)',
      '(1.9%)',
      '(2.2%)',
      '(2.3%)',
      '(5.1%)',
      '(3.7%)'],
     ['세전이익',
      '△5,175',
      '1,788',
      '555',
      '2,343',
      '2,072',
      '4,415',
      '425',
      '△1,163',
      '△738'],
     ['(%)',
      '(△3.9%)',
      '(5.6%)',
      '(1.4%)',
      '(3.8%)',
      '(3.2%)',
      '(3.4%)',
      '(1.4%)',
      '(△3.6%)',
      '(△1.1%)']],
    'row_count': 5,
    'column_count': 10}],
  'markdown': "| 구분 | '23年 | '24年 1Q | '24年 2Q | '24年 24上 | '24年 24下 | '24年 계 | '25年 1Q | '25年 2Q | '25年 25上 |\n|---|---|---|---|---|---|---|---|---|---|\n| 매출액 | 13.4 | 3.1 | 3.3 | 6.4 | 6.5 | 12.9 | 3.1 | 3.2 | 6.3 |\n| 영업이익 | △3,879 | 705 | 934 | 1,639 | 1,221 | 2,860 | 704 | 1,620 | 2,324 |\n| (%) | (△2.9%) | (2.3%) | (2.3%) | (2.6%) | (1.9%) | (2.2%) | (2.3%) | (5.1%) | (3.7%) |\n| 세전이익 | △5,175 | 1,788 | 555 | 2,343 | 2,072 | 4,415 | 425 | △1,163 | △738 |\n| (%) | (△3.9%) | (5.6%) | (1.4%) | (3.8%) | (3.2%) | (3.4%) | (1.4%) | (△3.6%) | (△1.1%) |",
  'summary': '1개의 표가 발견되었습니다. 이 표는 2023년부터 2025년까지의 매출액, 영업이익, 세전이익을 분기별로 나타내고 있습니다.',
  'table_count': 1,
  'extraction_method': 'OpenAI API (gpt-4o)'},
 {'success': True,
  'tables': [{'table_id': 'table_1',
    'title': '(매출: 조원, 이익: 억원)',
    'headers': ['', "'23年", "'24年", '', '', "'25年", ''],
    'rows': [['', '4個期', '1Q', '2Q', '24上', '24下', '計', '1Q', '2Q', '25上'],
     ['매출액',
      '11.6',
      '2.5',
      '2.8',
      '2.5',
      '3.5',
      '5.2',
      '10.5',
      '2.1',
      '2.3',
      '4.4'],
     ['영업이익',
      '6,625',
      '1,148',
      '1,048',
      '2,196',
      '1,835',
      '4,031',
      '1,513',
      '822',
      '2,335'],
     ['(%)',
      '(5.7)',
      '(4.6)',
      '(3.6)',
      '(4.1)',
      '(3.5)',
      '(3.8)',
      '(7.3)',
      '(3.6)',
      '(5.4)'],
     ['세전이익',
      '7,450',
      '1,364',
      '1,353',
      '2,717',
      '868',
      '3,585',
      '957',
      '△511',
      '446'],
     ['(%)',
      '(6.4)',
      '(5.5)',
      '(4.8)',
      '(5.1)',
      '(1.7)',
      '(3.4)',
      '(4.6)',
      '(△2.2)',
      '(1.0)']],
    'row_count': 6,
    'column_count': 10}],
  'markdown': "|          | '23年 | '24年 |     |     |     | '25年 |     |\n|----------|-------|-------|-----|-----|-----|-------|-----|\n|          | 4個期 | 1Q    | 2Q  | 24上 | 24下 | 計    | 1Q  | 2Q  | 25上 |\n| 매출액   | 11.6  | 2.5   | 2.8 | 2.5 | 3.5 | 5.2   | 10.5 | 2.1 | 2.3 | 4.4 |\n| 영업이익 | 6,625 | 1,148 | 1,048 | 2,196 | 1,835 | 4,031 | 1,513 | 822 | 2,335 |\n| (%)      | (5.7) | (4.6) | (3.6) | (4.1) | (3.5) | (3.8) | (7.3) | (3.6) | (5.4) |\n| 세전이익 | 7,450 | 1,364 | 1,353 | 2,717 | 868 | 3,585 | 957 | △511 | 446 |\n| (%)      | (6.4) | (5.5) | (4.8) | (5.1) | (1.7) | (3.4) | (4.6) | (△2.2) | (1.0) |",
  'summary': '1개의 표가 발견되었습니다. 이 표는 매출액과 이익에 대한 연도별 및 분기별 데이터를 포함하고 있습니다.',
  'table_count': 1,
  'extraction_method': 'OpenAI API (gpt-4o)'},
 {'success': True,
  'tables': [{'table_id': 'table_1',
    'title': '(매출: 조원, 이익: 억원)',
    'headers': ['',
     "'23年 年間",
     "'24年 1Q",
     "'24年 2Q",
     "'24年 上",
     "'24年 下",
     "'24年 계",
     "'25年 1Q",
     "'25年 2Q",
     "'25年 上"],
    'rows': [['매출액',
      '8.0',
      '1.9',
      '2.1',
      '4.0',
      '4.3',
      '8.3',
      '1.8',
      '2.0',
      '3.8'],
     ['영업이익',
      '3,307',
      '609',
      '326',
      '935',
      '1,774',
      '2,709',
      '810',
      '1,262',
      '2,072'],
     ['(%)',
      '(4.1%)',
      '(3.2%)',
      '(2.6%)',
      '(2.4%)',
      '(4.1%)',
      '(3.3%)',
      '(4.5%)',
      '(6.3%)',
      '(5.5%)'],
     ['세전이익',
      '2,798',
      '441',
      '560',
      '1,001',
      '1,538',
      '2,538',
      '425',
      '247',
      '672'],
     ['(%)',
      '(3.5%)',
      '(2.3%)',
      '(2.7%)',
      '(2.5%)',
      '(5.8%)',
      '(4.3%)',
      '(2.4%)',
      '(1.2%)',
      '(1.8%)']],
    'row_count': 5,
    'column_count': 10}],
  'markdown': "|          | '23年 年間 | '24年 1Q | '24年 2Q | '24年 上 | '24年 下 | '24年 계 | '25年 1Q | '25年 2Q | '25年 上 |\n|----------|------------|----------|----------|----------|----------|----------|----------|----------|----------|\n| 매출액   | 8.0        | 1.9      | 2.1      | 4.0      | 4.3      | 8.3      | 1.8      | 2.0      | 3.8      |\n| 영업이익 | 3,307      | 609      | 326      | 935      | 1,774    | 2,709    | 810      | 1,262    | 2,072    |\n| (%)      | (4.1%)     | (3.2%)   | (2.6%)   | (2.4%)   | (4.1%)   | (3.3%)   | (4.5%)   | (6.3%)   | (5.5%)   |\n| 세전이익 | 2,798      | 441      | 560      | 1,001    | 1,538    | 2,538    | 425      | 247      | 672      |\n| (%)      | (3.5%)     | (2.3%)   | (2.7%)   | (2.5%)   | (5.8%)   | (4.3%)   | (2.4%)   | (1.2%)   | (1.8%)   |",
  'summary': '1개의 표가 발견되었습니다. 이 표는 매출액과 이익에 대한 연도별 분기 데이터를 포함하고 있습니다.',
  'table_count': 1,
  'extraction_method': 'OpenAI API (gpt-4o)'}]

In [3]:
from process_analyze_data import AnalyzeDataProcessor

# 커스텀 설정
processor = AnalyzeDataProcessor(api_url="http://localhost:8000")

# 특정 모델로 처리
results = processor.process_all_images(model="gpt-4o")

🔍 5개의 PNG 파일 발견
==================================================

[1/5] foreign_sample1.png
처리 중: foreign_sample1.png
✅ 성공: 1개 표 발견
💾 결과 저장: result\foreign_sample1_result.json
⏳ 1.0초 대기...

[2/5] foreign_sample2.png
처리 중: foreign_sample2.png
✅ 성공: 1개 표 발견
💾 결과 저장: result\foreign_sample2_result.json
⏳ 1.0초 대기...

[3/5] foreign_sample3.png
처리 중: foreign_sample3.png
✅ 성공: 2개 표 발견
💾 결과 저장: result\foreign_sample3_result.json
⏳ 1.0초 대기...

[4/5] foreign_sample4.png
처리 중: foreign_sample4.png
✅ 성공: 1개 표 발견
💾 결과 저장: result\foreign_sample4_result.json
⏳ 1.0초 대기...

[5/5] foreign_sample5.png
처리 중: foreign_sample5.png
✅ 성공: 1개 표 발견
💾 결과 저장: result\foreign_sample5_result.json